stages:
  - test

test-py:
  stage: test
  image: "python:3.8"
  script:
    - pip install -r requirements.txt
    - pytest --cov=src tests
    - coverage xml --include="src/**" -o reports/coverage.xml
    - sed -i 's|" filename="|" filename="src/|g' reports/coverage.xml
  artifacts:
    paths:
      - reports/coverage.xml
    reports:
      cobertura:
        - reports/coverage.xml
