run tests:
  stage: test
  image: python:3
  script:
    - pip install pytest pytest-cov
    - pytest --cov=src/ tests/test_simple.py
    - coverage xml
    - sed -i 's|" filename="|" filename="src/|g' coverage.xml
  artifacts:
    paths:
      - coverage.xml
    reports:
      cobertura: coverage.xml

